// Comprehensive car-brand list for the storefront brand picker. Logos live in
// /public/brand-logos/{slug}.png. Generated from the car-logos dataset; every
// brand is searchable so parts can be found for any car.
export type CarBrand = { name: string; slug: string; logo: boolean };

export const CAR_BRANDS: CarBrand[] = [
  { name: "Abarth", slug: "abarth", logo: true },
  { name: "Acura", slug: "acura", logo: true },
  { name: "Alfa Romeo", slug: "alfa-romeo", logo: true },
  { name: "Alpine", slug: "alpine", logo: true },
  { name: "Aston Martin", slug: "aston-martin", logo: true },
  { name: "Audi", slug: "audi", logo: true },
  { name: "Bentley", slug: "bentley", logo: true },
  { name: "BMW", slug: "bmw", logo: true },
  { name: "Bugatti", slug: "bugatti", logo: true },
  { name: "Buick", slug: "buick", logo: true },
  { name: "BYD", slug: "byd", logo: true },
  { name: "Cadillac", slug: "cadillac", logo: true },
  { name: "Changan", slug: "changan", logo: true },
  { name: "Chery", slug: "chery", logo: true },
  { name: "Chevrolet", slug: "chevrolet", logo: true },
  { name: "Chrysler", slug: "chrysler", logo: true },
  { name: "Citroen", slug: "citroen", logo: true },
  { name: "Dacia", slug: "dacia", logo: true },
  { name: "Daewoo", slug: "daewoo", logo: true },
  { name: "Daihatsu", slug: "daihatsu", logo: true },
  { name: "Datsun", slug: "datsun", logo: true },
  { name: "Dodge", slug: "dodge", logo: true },
  { name: "Dongfeng", slug: "dongfeng", logo: true },
  { name: "Ferrari", slug: "ferrari", logo: true },
  { name: "Fiat", slug: "fiat", logo: true },
  { name: "Ford", slug: "ford", logo: true },
  { name: "Foton", slug: "foton", logo: true },
  { name: "Geely", slug: "geely", logo: true },
  { name: "Genesis", slug: "genesis", logo: true },
  { name: "GMC", slug: "gmc", logo: true },
  { name: "Great Wall", slug: "great-wall", logo: true },
  { name: "Haval", slug: "haval", logo: true },
  { name: "Holden", slug: "holden", logo: true },
  { name: "Honda", slug: "honda", logo: true },
  { name: "Hongqi", slug: "hongqi", logo: true },
  { name: "Hummer", slug: "hummer", logo: true },
  { name: "Hyundai", slug: "hyundai", logo: true },
  { name: "Infiniti", slug: "infiniti", logo: true },
  { name: "Isuzu", slug: "isuzu", logo: true },
  { name: "JAC", slug: "jac", logo: true },
  { name: "Jaguar", slug: "jaguar", logo: true },
  { name: "Jeep", slug: "jeep", logo: true },
  { name: "Kia", slug: "kia", logo: true },
  { name: "Koenigsegg", slug: "koenigsegg", logo: true },
  { name: "Lada", slug: "lada", logo: true },
  { name: "Lamborghini", slug: "lamborghini", logo: true },
  { name: "Lancia", slug: "lancia", logo: true },
  { name: "Land Rover", slug: "land-rover", logo: true },
  { name: "Lexus", slug: "lexus", logo: true },
  { name: "Lincoln", slug: "lincoln", logo: true },
  { name: "Lotus", slug: "lotus", logo: true },
  { name: "Mahindra", slug: "mahindra", logo: true },
  { name: "Maserati", slug: "maserati", logo: true },
  { name: "Maybach", slug: "maybach", logo: true },
  { name: "Mazda", slug: "mazda", logo: true },
  { name: "McLaren", slug: "mclaren", logo: true },
  { name: "Mercedes-Benz", slug: "mercedes-benz", logo: true },
  { name: "MG", slug: "mg", logo: true },
  { name: "Mini", slug: "mini", logo: true },
  { name: "Mitsubishi", slug: "mitsubishi", logo: true },
  { name: "Nissan", slug: "nissan", logo: true },
  { name: "Opel", slug: "opel", logo: true },
  { name: "Pagani", slug: "pagani", logo: true },
  { name: "Perodua", slug: "perodua", logo: true },
  { name: "Peugeot", slug: "peugeot", logo: true },
  { name: "Polestar", slug: "polestar", logo: true },
  { name: "Pontiac", slug: "pontiac", logo: true },
  { name: "Porsche", slug: "porsche", logo: true },
  { name: "Proton", slug: "proton", logo: true },
  { name: "RAM", slug: "ram", logo: true },
  { name: "Renault", slug: "renault", logo: true },
  { name: "Rolls-Royce", slug: "rolls-royce", logo: true },
  { name: "Saab", slug: "saab", logo: true },
  { name: "Seat", slug: "seat", logo: true },
  { name: "Skoda", slug: "skoda", logo: true },
  { name: "Smart", slug: "smart", logo: true },
  { name: "SsangYong", slug: "ssangyong", logo: true },
  { name: "Subaru", slug: "subaru", logo: true },
  { name: "Suzuki", slug: "suzuki", logo: true },
  { name: "Tata", slug: "tata", logo: true },
  { name: "Tesla", slug: "tesla", logo: true },
  { name: "Toyota", slug: "toyota", logo: true },
  { name: "Vauxhall", slug: "vauxhall", logo: true },
  { name: "Volkswagen", slug: "volkswagen", logo: true },
  { name: "Volvo", slug: "volvo", logo: true },
];

// Brands surfaced as tiles before the customer searches (UAE-popular).
export const POPULAR_SLUGS = ["toyota","nissan","mitsubishi","honda","lexus","mercedes-benz","hyundai","ford"];
