// Part suggestions for the two inquiry tiles. Free text is always allowed.
// "Find Auto Parts"  -> AUTO_PARTS (everything mechanical/electrical/service)
// "Find Body Parts"  -> BODY_PARTS (exterior body & glass + interior)
export const AUTO_PARTS: string[] = [
  // Service / filters / engine
  "Engine oil",
  "Oil filter",
  "Air filter",
  "Cabin air filter",
  "Fuel filter",
  "Spark plugs",
  "Glow plugs",
  "Ignition coil",
  "Timing belt",
  "Timing chain",
  "Serpentine belt",
  "Drive belt",
  "Water pump",
  "Radiator",
  "Radiator fan",
  "Cooling fan",
  "Thermostat",
  "Coolant / antifreeze",
  "Engine mount",
  "Valve cover gasket",
  "Head gasket",
  "Cylinder head",
  "Turbocharger",
  "Intercooler",
  "Throttle body",
  "Fuel pump",
  "Fuel injector",
  "PCV valve",
  "EGR valve",
  "Vacuum pump",
  "Oxygen (O2) sensor",
  "Mass air flow sensor",
  "Crankshaft sensor",
  "Camshaft sensor",
  "Engine assembly",
  // Brakes
  "Brake pads",
  "Brake discs / rotors",
  "Brake caliper",
  "Brake master cylinder",
  "Brake booster",
  "Brake hose",
  "Brake fluid",
  "ABS sensor",
  "Wheel cylinder",
  "Handbrake cable",
  // Suspension & steering
  "Shock absorber",
  "Strut assembly",
  "Coil spring",
  "Control arm",
  "Lower control arm",
  "Ball joint",
  "Tie rod end",
  "Tie rod",
  "Steering rack",
  "Power steering pump",
  "Stabilizer / sway bar link",
  "Suspension bushing",
  "Wheel bearing",
  "Wheel hub",
  "CV joint",
  "CV axle / drive shaft",
  // Transmission & drivetrain
  "Clutch kit",
  "Clutch master cylinder",
  "Flywheel",
  "Gearbox / transmission",
  "Transmission mount",
  "Differential",
  "Propeller shaft",
  // Electrical
  "Battery",
  "Alternator",
  "Starter motor",
  "Fuse box",
  "Relay",
  "Wiring harness",
  "ECU / engine computer",
  "Ignition switch",
  "Horn",
  // Lighting
  "Headlight",
  "Headlight bulb",
  "Tail light",
  "Fog light",
  "Turn signal / indicator",
  "Brake light",
  "Xenon ballast",
  // AC & heating
  "AC compressor",
  "AC condenser",
  "AC evaporator",
  "Expansion valve",
  "Blower motor",
  "Heater core",
  // Exhaust
  "Exhaust pipe",
  "Muffler",
  "Catalytic converter",
  "Exhaust manifold",
  "DPF filter",
  // Wheels / fuel
  "Tyre",
  "Alloy wheel",
  "Wheel nut",
  "TPMS sensor",
  "Fuel tank",
  "Fuel cap",
];

export const BODY_PARTS: string[] = [
  // Body & glass
  "Front bumper",
  "Rear bumper",
  "Fender",
  "Bonnet / hood",
  "Boot / trunk lid",
  "Front door",
  "Rear door",
  "Door handle",
  "Side mirror",
  "Mirror glass",
  "Windshield / windscreen",
  "Rear windscreen",
  "Door window glass",
  "Grille",
  "Wiper blades",
  "Wiper motor",
  "Wiper arm",
  "Mud flap",
  "Splash guard",
  // Interior & safety
  "Dashboard",
  "Door panel",
  "Seat",
  "Seat belt",
  "Airbag",
  "Steering wheel",
  "Steering column",
];

// Combined list (kept for anything that wants the full catalogue).
export const CAR_PARTS: string[] = [...AUTO_PARTS, ...BODY_PARTS];

