// Part suggestions for the two inquiry tiles. Free text is always allowed.
// "Find Auto Parts"  -> AUTO_PARTS (everything mechanical/electrical/service)
// "Find Body Parts"  -> BODY_PARTS (exterior body & glass + interior)
export const AUTO_PARTS: string[] = [
  // Service / filters / engine
  "Engine oil",
  "Oil filter",
  "Air filter",
  "Cabin air filter",
  "Fuel filter",
  "Spark plugs",
  "Glow plugs",
  "Ignition coil",
  "Timing belt",
  "Timing chain",
  "Serpentine belt",
  "Drive belt",
  "Water pump",
  "Radiator",
  "Radiator fan",
  "Cooling fan",
  "Thermostat",
  "Coolant / antifreeze",
  "Engine mount",
  "Valve cover gasket",
  "Head gasket",
  "Cylinder head",
  "Turbocharger",
  "Intercooler",
  "Throttle body",
  "Fuel pump",
  "Fuel injector",
  "PCV valve",
  "EGR valve",
  "Vacuum pump",
  "Oxygen (O2) sensor",
  "Mass air flow sensor",
  "Crankshaft sensor",
  "Camshaft sensor",
  "Engine assembly",
  // Brakes
  "Brake pads",
  "Brake discs / rotors",
  "Brake caliper",
  "Brake master cylinder",
  "Brake booster",
  "Brake hose",
  "Brake fluid",
  "ABS sensor",
  "Wheel cylinder",
  "Handbrake cable",
  // Suspension & steering
  "Shock absorber",
  "Strut assembly",
  "Coil spring",
  "Control arm",
  "Lower control arm",
  "Ball joint",
  "Tie rod end",
  "Tie rod",
  "Steering rack",
  "Power steering pump",
  "Stabilizer / sway bar link",
  "Suspension bushing",
  "Wheel bearing",
  "Wheel hub",
  "CV joint",
  "CV axle / drive shaft",
  // Transmission & drivetrain
  "Clutch kit",
  "Clutch master cylinder",
  "Flywheel",
  "Gearbox / transmission",
  "Transmission mount",
  "Differential",
  "Propeller shaft",
  // Electrical
  "Battery",
  "Alternator",
  "Starter motor",
  "Fuse box",
  "Relay",
  "Wiring harness",
  "ECU / engine computer",
  "Ignition switch",
  "Horn",
  // Lighting
  "Headlight",
  "Headlight bulb",
  "Tail light",
  "Fog light",
  "Turn signal / indicator",
  "Brake light",
  "Xenon ballast",
  // AC & heating
  "AC compressor",
  "AC condenser",
  "AC evaporator",
  "Expansion valve",
  "Blower motor",
  "Heater core",
  // Exhaust
  "Exhaust pipe",
  "Muffler",
  "Catalytic converter",
  "Exhaust manifold",
  "DPF filter",
  // Wheels / fuel
  "Tyre",
  "Alloy wheel",
  "Wheel nut",
  "TPMS sensor",
  "Fuel tank",
  "Fuel cap",
];

export const BODY_PARTS: string[] = [
  // Body & glass
  "Front bumper",
  "Rear bumper",
  "Fender",
  "Bonnet / hood",
  "Boot / trunk lid",
  "Front door",
  "Rear door",
  "Door handle",
  "Side mirror",
  "Mirror glass",
  "Windshield / windscreen",
  "Rear windscreen",
  "Door window glass",
  "Grille",
  "Wiper blades",
  "Wiper motor",
  "Wiper arm",
  "Mud flap",
  "Splash guard",
  // Interior & safety
  "Dashboard",
  "Door panel",
  "Seat",
  "Seat belt",
  "Airbag",
  "Steering wheel",
  "Steering column",
];


// Full A–Z catalogue supplied by the owner. Appended after the curated lists
// above so the familiar popular parts still lead the dropdown; anything here
// that already appeared above was dropped, so nothing shows twice.
export const MASTER_PARTS: string[] = [
  "ABS Accumulator",
  "ABS Actuator",
  "ABS Control Module",
  "ABS Hydraulic Unit",
  "ABS Modulator",
  "ABS Pump",
  "ABS Relay",
  "ABS Speed Sensor",
  "ABS Tone Ring",
  "AC Accumulator",
  "AC Blower Motor",
  "AC Blower Resistor",
  "AC Compressor Clutch",
  "AC Compressor Coil",
  "AC Compressor Pulley",
  "AC Condenser Fan",
  "AC Condenser Fan Motor",
  "AC Control Module",
  "AC Control Panel",
  "AC Expansion Valve",
  "AC Filter",
  "AC Hose",
  "AC Pipe",
  "AC Pressure Sensor",
  "AC Receiver Drier",
  "AC Relay",
  "AC Service Port",
  "AC Solenoid",
  "AC Temperature Sensor",
  "AC Thermistor",
  "AC Valve",
  "AC Vent",
  "AC Vent Grille",
  "AC Vent Motor",
  "Accelerator Cable",
  "Accelerator Pedal",
  "Accelerator Pedal Position Sensor",
  "Accelerator Pedal Sensor",
  "Accessory Belt",
  "Accessory Belt Tensioner",
  "Accessory Drive Belt",
  "Accessory Pulley",
  "Active Grille Shutter",
  "Active Suspension Actuator",
  "Active Suspension Compressor",
  "Active Suspension Control Module",
  "Adaptive Cruise Control Module",
  "Adaptive Cruise Control Radar",
  "AdBlue Injector",
  "AdBlue Pump",
  "AdBlue Tank",
  "AdBlue Heater",
  "AdBlue Level Sensor",
  "AdBlue Temperature Sensor",
  "AdBlue Line",
  "Air Cleaner",
  "Air Cleaner Assembly",
  "Air Cleaner Box",
  "Air Cleaner Element",
  "Air Cleaner Hose",
  "Air Cleaner Housing",
  "Air Cleaner Intake Duct",
  "Air Cleaner Lid",
  "Air Cleaner Mount",
  "Air Cleaner Resonator",
  "Air Cleaner Seal",
  "Air Cleaner Tube",
  "Air Conditioning Compressor",
  "Air Conditioning Control Module",
  "Air Conditioning Control Panel",
  "Air Conditioning Filter",
  "Air Conditioning Hose",
  "Air Conditioning Pipe",
  "Air Conditioning Relay",
  "Air Conditioning Switch",
  "Air Control Valve",
  "Air Deflector",
  "Air Duct",
  "Air Filter Housing",
  "Air Filter Element",
  "Air Flow Meter",
  "Air Guide",
  "Air Intake Boot",
  "Air Intake Duct",
  "Air Intake Hose",
  "Air Intake Manifold",
  "Air Intake Pipe",
  "Air Intake Resonator",
  "Air Intake Tube",
  "Air Injection Pump",
  "Air Injection Valve",
  "Air Mass Meter",
  "Air Pump",
  "Air Suspension Compressor",
  "Air Suspension Control Module",
  "Air Suspension Height Sensor",
  "Air Suspension Valve Block",
  "Air Temperature Sensor",
  "Air Vent",
  "Air Vent Grille",
  "Airbag Clock Spring",
  "Airbag Control Module",
  "Airbag Cushion",
  "Airbag Inflator",
  "Airbag Module",
  "Airbag Sensor",
  "Airbag Wiring Harness",
  "Alarm Horn",
  "Alarm Siren",
  "Alternator Bearing",
  "Alternator Belt",
  "Alternator Brush",
  "Alternator Clutch Pulley",
  "Alternator Diode",
  "Alternator Fan",
  "Alternator Mount",
  "Alternator Pulley",
  "Alternator Regulator",
  "Alternator Rotor",
  "Alternator Stator",
  "Ambient Air Temperature Sensor",
  "Amplifier",
  "Antenna",
  "Antenna Base",
  "Antenna Cable",
  "Antenna Mast",
  "Anti-Roll Bar",
  "Anti-Roll Bar Bush",
  "Anti-Roll Bar Link",
  "Anti-Theft Control Module",
  "Armrest",
  "Armrest Console",
  "Armrest Cover",
  "Armrest Hinge",
  "Armrest Pad",
  "Armrest Trim",
  "Ashtray",
  "Ashtray Assembly",
  "Ashtray Cover",
  "Auxiliary Battery",
  "Auxiliary Battery Cable",
  "Auxiliary Battery Relay",
  "Auxiliary Fuse Box",
  "Auxiliary Water Pump",
  "Axle",
  "Axle Bearing",
  "Axle Boot",
  "Axle Hub",
  "Axle Seal",
  "Axle Shaft",
  "Axle Shaft Bearing",
  "Axle Shaft Seal",
  "Axle Tube",
  "Back Door",
  "Back Door Actuator",
  "Back Door Handle",
  "Back Door Hinge",
  "Back Door Lock",
  "Back Door Lock Actuator",
  "Back Door Lock Cylinder",
  "Back Door Latch",
  "Back Door Striker",
  "Back Door Weatherstrip",
  "Back Glass",
  "Backup Camera",
  "Backup Camera Bracket",
  "Backup Light",
  "Ball Bearing",
  "Ball Joint Boot",
  "Ball Joint Dust Cover",
  "Ball Joint Repair Kit",
  "Ball Joint Retainer",
  "Ball Joint Stud",
  "Ballast",
  "Battery Box",
  "Battery Cable",
  "Battery Case",
  "Battery Clamp",
  "Battery Cover",
  "Battery Current Sensor",
  "Battery Disconnect Switch",
  "Battery Ground Cable",
  "Battery Holder",
  "Battery Insulator",
  "Battery Junction Box",
  "Battery Management System",
  "Battery Mount",
  "Battery Post",
  "Battery Retainer",
  "Battery Terminal",
  "Battery Terminal Cover",
  "Battery Tray",
  "Battery Vent",
  "Battery Vent Hose",
  "Battery Voltage Sensor",
  "Battery Water",
  "Bed Liner",
  "Bed Rail",
  "Bed Tailgate",
  "Bed Tie Down",
  "Bedside",
  "Belt",
  "Belt Idler",
  "Belt Tensioner",
  "Bell Housing",
  "Blower Fan",
  "Blower Motor Resistor",
  "Blower Motor Relay",
  "Blower Wheel",
  "Brake Booster Check Valve",
  "Brake Caliper Bracket",
  "Brake Caliper Guide Pin",
  "Brake Caliper Guide Pin Boot",
  "Brake Caliper Piston",
  "Brake Caliper Repair Kit",
  "Brake Caliper Seal",
  "Brake Caliper Slide",
  "Brake Caliper Spring",
  "Brake Caliper Support",
  "Brake Disc",
  "Brake Disc Dust Shield",
  "Brake Disc Guard",
  "Brake Disc Retainer",
  "Brake Drum",
  "Brake Drum Backing Plate",
  "Brake Drum Hardware Kit",
  "Brake Fluid Reservoir",
  "Brake Hose Bracket",
  "Brake Line",
  "Brake Line Clip",
  "Brake Line Connector",
  "Brake Line Joint",
  "Brake Light Bulb",
  "Brake Light Switch",
  "Brake Master Cylinder Cap",
  "Brake Master Cylinder Reservoir",
  "Brake Pad",
  "Brake Pad Backing Plate",
  "Brake Pad Clip",
  "Brake Pad Hardware",
  "Brake Pad Shim",
  "Brake Pad Spring",
  "Brake Pedal",
  "Brake Pedal Pad",
  "Brake Pressure Sensor",
  "Brake Proportioning Valve",
  "Brake Rotor",
  "Brake Shoe",
  "Brake Shoe Adjuster",
  "Brake Shoe Hardware Kit",
  "Brake Shoe Hold-Down Pin",
  "Brake Shoe Return Spring",
  "Brake Shoe Wheel Cylinder",
  "Brake Vacuum Pump",
  "Brake Wear Sensor",
  "Brake Wheel Cylinder",
  "Breather Hose",
  "Breather Valve",
  "Bumper",
  "Bumper Absorber",
  "Bumper Beam",
  "Bumper Bracket",
  "Bumper Cover",
  "Bumper Grille",
  "Bumper Guide",
  "Bumper Impact Absorber",
  "Bumper Mount",
  "Bumper Reinforcement",
  "Bumper Retainer",
  "Bumper Support",
  "Bumper Trim",
  "Bush",
  "Bush Kit",
  "Bushing",
  "Bushing Bracket",
  "Bushing Sleeve",
  "Button Switch",
  "Cabin Filter",
  "Cabin Filter Housing",
  "Cabin Temperature Sensor",
  "Cam Follower",
  "Cam Gear",
  "Cam Seal",
  "Camshaft",
  "Camshaft Bearing",
  "Camshaft Cap",
  "Camshaft Cover",
  "Camshaft Gear",
  "Camshaft Position Sensor",
  "Camshaft Pulley",
  "Camshaft Seal",
  "Camshaft Sprocket",
  "Camshaft Tensioner",
  "Camshaft Variable Timing Actuator",
  "Canister",
  "Canister Purge Valve",
  "Carburetor",
  "Carburetor Gasket",
  "Carburetor Repair Kit",
  "Carburetor Solenoid",
  "Catalytic Converter Gasket",
  "Catalytic Converter Heat Shield",
  "Center Console",
  "Center Console Armrest",
  "Center Console Lid",
  "Center Console Trim",
  "Center Differential",
  "Center Support Bearing",
  "Center Support Bearing Bracket",
  "Center Wheel Cap",
  "Charge Air Cooler",
  "Charge Air Pipe",
  "Charging Cable",
  "Charging Inlet",
  "Charging Port",
  "Chassis Control Module",
  "Chassis Harness",
  "Chassis Mount",
  "Clutch",
  "Clutch Actuator",
  "Clutch Bearing",
  "Clutch Cable",
  "Clutch Cover",
  "Clutch Disc",
  "Clutch Fork",
  "Clutch Fork Boot",
  "Clutch Hose",
  "Clutch Pedal",
  "Clutch Pedal Pad",
  "Clutch Pressure Plate",
  "Clutch Release Bearing",
  "Clutch Slave Cylinder",
  "Clutch Slave Cylinder Seal",
  "Clutch Switch",
  "Clutch Throwout Bearing",
  "Coil Spring Insulator",
  "Coil Spring Pad",
  "Coilover",
  "Combination Meter",
  "Combination Switch",
  "Combination Valve",
  "Combustion Chamber",
  "Control Arm Assembly",
  "Control Arm Ball Joint",
  "Control Arm Bolt",
  "Control Arm Bushing",
  "Control Arm Bracket",
  "Control Arm Repair Kit",
  "Coolant",
  "Coolant Bypass Hose",
  "Coolant Flange",
  "Coolant Hose",
  "Coolant Level Sensor",
  "Coolant Pipe",
  "Coolant Reservoir",
  "Coolant Reservoir Cap",
  "Coolant Temperature Sensor",
  "Cooling Fan Assembly",
  "Cooling Fan Clutch",
  "Cooling Fan Motor",
  "Cooling Fan Relay",
  "Cooling Fan Shroud",
  "Cooling System Hose",
  "Cornering Lamp",
  "Crankcase",
  "Crankcase Breather",
  "Crankcase Vent Hose",
  "Crankcase Vent Valve",
  "Crankshaft",
  "Crankshaft Bearing",
  "Crankshaft Bolt",
  "Crankshaft Gear",
  "Crankshaft Position Sensor",
  "Crankshaft Pulley",
  "Crankshaft Seal",
  "Crankshaft Sprocket",
  "Cruise Control Module",
  "Cruise Control Switch",
  "Cylinder Head Bolt",
  "Cylinder Head Cover",
  "Cylinder Head Gasket",
  "Cylinder Head Seal",
  "Cylinder Liner",
  "Cylinder Sleeve",
  "Dashboard Air Vent",
  "Dashboard Control Panel",
  "Dashboard Trim",
  "Dash Camera",
  "Dash Panel",
  "Daytime Running Light",
  "Defroster Duct",
  "Defroster Grille",
  "Defroster Motor",
  "Diesel Injector",
  "Diesel Injection Pump",
  "Diesel Particulate Filter",
  "Differential Bearing",
  "Differential Carrier",
  "Differential Cover",
  "Differential Gear",
  "Differential Gasket",
  "Differential Mount",
  "Differential Pinion",
  "Differential Pinion Bearing",
  "Differential Pinion Seal",
  "Differential Ring Gear",
  "Differential Side Gear",
  "Differential Side Seal",
  "Differential Spider Gear",
  "Differential Oil",
  "Differential Oil Seal",
  "Distributor",
  "Distributor Cap",
  "Distributor Rotor",
  "Door",
  "Door Armrest",
  "Door Check",
  "Door Check Strap",
  "Door Cladding",
  "Door Handle Bezel",
  "Door Hinge",
  "Door Lock",
  "Door Lock Actuator",
  "Door Lock Cylinder",
  "Door Lock Knob",
  "Door Lock Motor",
  "Door Latch",
  "Door Mirror",
  "Door Pocket",
  "Door Pull",
  "Door Seal",
  "Door Speaker",
  "Door Striker",
  "Door Switch",
  "Door Trim",
  "Door Weatherstrip",
  "Door Window",
  "Door Window Regulator",
  "Door Window Switch",
  "Door Window Motor",
  "Drive Belt Idler",
  "Drive Belt Tensioner",
  "Drive Gear",
  "Drive Shaft",
  "Drive Shaft Bearing",
  "Drive Shaft Center Bearing",
  "Drive Shaft Coupling",
  "Drive Shaft Flange",
  "Drive Shaft Joint",
  "Drive Shaft Support",
  "Drive Sprocket",
  "Driver Information Display",
  "Dust Cap",
  "Dust Cover",
  "Dust Shield",
  "Dynamic Stability Control Module",
  "EGR Cooler",
  "EGR Gasket",
  "EGR Pipe",
  "EGR Solenoid",
  "Electric Coolant Pump",
  "Electric Motor",
  "Electric Power Steering Motor",
  "Electric Water Pump",
  "Electronic Brake Control Module",
  "Electronic Parking Brake Actuator",
  "Electronic Throttle Body",
  "Emergency Brake Cable",
  "Emergency Brake Handle",
  "Emergency Brake Lever",
  "Engine Block",
  "Engine Bracket",
  "Engine Cover",
  "Engine Cradle",
  "Engine Gasket Set",
  "Engine Ground Strap",
  "Engine Harness",
  "Engine Mount Bracket",
  "Engine Mount Insulator",
  "Engine Oil Cooler",
  "Engine Oil Cooler Hose",
  "Engine Oil Dipstick",
  "Engine Oil Drain Plug",
  "Engine Oil Filter",
  "Engine Oil Pan",
  "Engine Oil Pan Gasket",
  "Engine Oil Pressure Sensor",
  "Engine Oil Pump",
  "Engine Oil Separator",
  "Engine Oil Temperature Sensor",
  "Engine Speed Sensor",
  "Engine Support",
  "Engine Timing Cover",
  "Engine Valve",
  "Engine Valve Cover",
  "Engine Valve Cover Gasket",
  "Engine Wiring Harness",
  "EV Battery",
  "EV Battery Cooling Plate",
  "EV Battery Module",
  "EV Battery Pack",
  "EV Battery Tray",
  "EV Charge Controller",
  "EV Charging Cable",
  "EV Charging Port",
  "EV Inverter",
  "EV Motor",
  "EV Motor Controller",
  "EV Reduction Gearbox",
  "EV Service Disconnect",
  "EV Thermal Management Module",
  "Evaporative Emission Canister",
  "Evaporative Emission Hose",
  "Evaporator",
  "Evaporator Core",
  "Evaporator Housing",
  "Exhaust Clamp",
  "Exhaust Flex Pipe",
  "Exhaust Gasket",
  "Exhaust Hanger",
  "Exhaust Heat Shield",
  "Exhaust Manifold Gasket",
  "Exhaust Resonator",
  "Exhaust Spring",
  "Exhaust Valve",
  "Exhaust Valve Actuator",
  "Exhaust Gas Temperature Sensor",
  "Exhaust Gas Pressure Sensor",
  "Exhaust Muffler",
  "Expansion Tank",
  "Expansion Tank Cap",
  "Fan Belt",
  "Fan Blade",
  "Fan Clutch",
  "Fan Motor",
  "Fan Relay",
  "Fan Shroud",
  "Fender Bracket",
  "Fender Flare",
  "Fender Liner",
  "Fender Moulding",
  "Fender Splash Shield",
  "Fender Trim",
  "Flywheel Bolt",
  "Flywheel Ring Gear",
  "Fog Light Bezel",
  "Fog Light Bulb",
  "Fog Light Housing",
  "Fog Light Switch",
  "Fuel Filter Housing",
  "Fuel Gauge",
  "Fuel Gauge Sender",
  "Fuel Injector O-Ring",
  "Fuel Injector Rail",
  "Fuel Level Sensor",
  "Fuel Line",
  "Fuel Line Connector",
  "Fuel Pressure Regulator",
  "Fuel Pressure Sensor",
  "Fuel Pump Control Module",
  "Fuel Pump Driver Module",
  "Fuel Pump Housing",
  "Fuel Pump Module",
  "Fuel Pump Relay",
  "Fuel Rail",
  "Fuel Rail Pressure Sensor",
  "Fuel Tank Cap",
  "Fuel Tank Filler Neck",
  "Fuel Tank Strap",
  "Fuel Tank Vent Valve",
  "Fuel Temperature Sensor",
  "Fuel Vapor Line",
  "Fuel Vapor Separator",
  "Fuse",
  "Fuse Holder",
  "Fuse Link",
  "Fuse Relay Box",
  "Fuse Terminal",
  "Front Bumper Cover",
  "Front Bumper Reinforcement",
  "Front Door Glass",
  "Front Door Handle",
  "Front Door Lock",
  "Front Door Speaker",
  "Front Door Trim",
  "Front Grille",
  "Front Lower Control Arm",
  "Front Upper Control Arm",
  "Gauge Cluster",
  "Gear",
  "Gear Lever",
  "Gear Lever Boot",
  "Gear Lever Cable",
  "Gear Lever Knob",
  "Gear Oil",
  "Gear Selector",
  "Gear Selector Cable",
  "Gear Selector Module",
  "Gear Shift Actuator",
  "Gear Shift Cable",
  "Gear Shift Fork",
  "Gear Shift Knob",
  "Gear Shift Linkage",
  "Gear Shift Motor",
  "Gearbox",
  "Gearbox Bearing",
  "Gearbox Case",
  "Gearbox Cover",
  "Gearbox Mount",
  "Gearbox Oil",
  "Gearbox Oil Cooler",
  "Gearbox Seal",
  "Glove Box",
  "Glove Box Door",
  "Glove Box Lock",
  "Glove Box Latch",
  "Glove Box Light",
  "Glove Box Striker",
  "Glow Plug",
  "Glow Plug Controller",
  "Glow Plug Relay",
  "Glow Plug Module",
  "GPS Antenna",
  "GPS Module",
  "Grille Badge",
  "Grille Emblem",
  "Grille Insert",
  "Grille Shutter",
  "Grille Surround",
  "Ground Cable",
  "Ground Strap",
  "Guide Pin",
  "Guide Pin Boot",
  "Hand Brake Cable",
  "Hand Brake Lever",
  "Hand Brake Switch",
  "Hazard Light Switch",
  "Headlamp",
  "Headlamp Assembly",
  "Headlamp Ballast",
  "Headlamp Bulb",
  "Headlamp Control Module",
  "Headlamp Housing",
  "Headlamp Level Sensor",
  "Headlamp Motor",
  "Headlamp Washer",
  "Headlamp Washer Cover",
  "Headlamp Washer Pump",
  "Headlamp Washer Nozzle",
  "Headlamp Wiring",
  "Head Restraint",
  "Headliner",
  "Headliner Console",
  "Headliner Trim",
  "Heater Blower Motor",
  "Heater Control Valve",
  "Heater Hose",
  "Heater Matrix",
  "Heater Pipe",
  "Heater Resistor",
  "Heater Valve",
  "Heated Seat Element",
  "High Pressure Fuel Pump",
  "High Pressure Fuel Pipe",
  "High Pressure Fuel Pump Sensor",
  "High Pressure Oil Pump",
  "High Voltage Battery",
  "High Voltage Battery Cable",
  "High Voltage Battery Connector",
  "High Voltage Battery Module",
  "High Voltage Fuse",
  "High Voltage Inverter",
  "High Voltage Relay",
  "High Voltage Service Plug",
  "Horn Relay",
  "Hood",
  "Hood Cable",
  "Hood Hinge",
  "Hood Insulator",
  "Hood Latch",
  "Hood Lock",
  "Hood Prop Rod",
  "Hood Strut",
  "Hood Support",
  "Hood Weatherstrip",
  "Hose",
  "Hose Clamp",
  "Hub",
  "Hub Bearing",
  "Hub Cap",
  "Hub Seal",
  "Hydraulic Clutch Line",
  "Hydraulic Control Unit",
  "Hydraulic Filter",
  "Hydraulic Pump",
  "Hydraulic Valve",
  "Idle Air Control Valve",
  "Idle Control Valve",
  "Idler Arm",
  "Idler Bearing",
  "Idler Pulley",
  "Ignition Coil Boot",
  "Ignition Control Module",
  "Ignition Lock Cylinder",
  "Ignition Relay",
  "Ignition Wire",
  "Intake Camshaft",
  "Intake Camshaft Actuator",
  "Intake Camshaft Position Sensor",
  "Intake Manifold",
  "Intake Manifold Gasket",
  "Intake Manifold Runner",
  "Intake Manifold Runner Control",
  "Intake Manifold Valve",
  "Intake Pipe",
  "Intake Resonator",
  "Intake Runner",
  "Intake Valve",
  "Intake Valve Seal",
  "Intake Air Temperature Sensor",
  "Intercooler Hose",
  "Intercooler Pipe",
  "Intercooler Pump",
  "Inverter",
  "Inverter Cooling Pump",
  "Inverter Cooling System",
  "Inverter Module",
  "Instrument Cluster",
  "Instrument Cluster Lens",
  "Instrument Cluster Module",
  "Interior Door Handle",
  "Interior Door Trim",
  "Interior Light",
  "Interior Light Bulb",
  "Interior Mirror",
  "Interior Trim",
  "Intermediate Shaft",
  "Intermediate Shaft Bearing",
  "Intermediate Shaft Seal",
  "Inlet Manifold",
  "Inlet Valve",
  "Jack",
  "Jack Handle",
  "Jack Mount",
  "Jack Pad",
  "Jack Storage Bracket",
  "Junction Box",
  "Junction Connector",
  "Jumper Cable",
  "Key",
  "Key Battery",
  "Key Fob",
  "Key Fob Case",
  "Key Fob Cover",
  "Key Fob Housing",
  "Keyless Entry Antenna",
  "Keyless Entry Module",
  "Kick Panel",
  "Knock Sensor",
  "Knuckle",
  "Knuckle Bearing",
  "Knuckle Seal",
  "Lamp",
  "Lamp Assembly",
  "Lamp Ballast",
  "Lamp Bulb",
  "Lamp Housing",
  "Lamp Module",
  "Lamp Socket",
  "Lamp Switch",
  "Lane Departure Camera",
  "Lane Departure Warning Module",
  "Lane Keep Assist Camera",
  "Leaf Spring",
  "Leaf Spring Bushing",
  "Leaf Spring Hanger",
  "Leaf Spring Shackle",
  "Level Control Sensor",
  "License Plate Lamp",
  "License Plate Lamp Bulb",
  "License Plate Bracket",
  "License Plate Frame",
  "License Plate Light",
  "Liftgate",
  "Liftgate Actuator",
  "Liftgate Handle",
  "Liftgate Hinge",
  "Liftgate Latch",
  "Liftgate Lock",
  "Liftgate Lock Actuator",
  "Liftgate Striker",
  "Liftgate Strut",
  "Liftgate Weatherstrip",
  "Light Control Module",
  "Light Switch",
  "Lock Actuator",
  "Lock Cylinder",
  "Lock Pin",
  "Lock Rod",
  "Lock Striker",
  "Lower Ball Joint",
  "Lower Grille",
  "Lower Radiator Hose",
  "Lower Suspension Arm",
  "Lug Bolt",
  "Lug Nut",
  "Lug Nut Cap",
  "Lug Stud",
  "MAP Sensor",
  "Master Cylinder",
  "Master Cylinder Cap",
  "Master Cylinder Reservoir",
  "Mechanic's Jack",
  "Mirror",
  "Mirror Actuator",
  "Mirror Assembly",
  "Mirror Base",
  "Mirror Camera",
  "Mirror Cap",
  "Mirror Cover",
  "Mirror Heater",
  "Mirror Housing",
  "Mirror Indicator",
  "Mirror Motor",
  "Mirror Switch",
  "Mirror Turn Signal",
  "Motor Mount",
  "Motor Mount Bracket",
  "Motor Mount Insulator",
  "Muffler Hanger",
  "Muffler Mount",
  "Multimedia Control Module",
  "Multimedia Screen",
  "Multimedia Unit",
  "Navigation Antenna",
  "Navigation Control Module",
  "Navigation Display",
  "Navigation Screen",
  "Neutral Safety Switch",
  "NOx Sensor",
  "NOx Sensor Module",
  "Nut",
  "Nut Plate",
  "Oil Cooler",
  "Oil Cooler Adapter",
  "Oil Cooler Hose",
  "Oil Cooler Line",
  "Oil Dipstick",
  "Oil Dipstick Tube",
  "Oil Drain Plug",
  "Oil Filler Cap",
  "Oil Filter Housing",
  "Oil Filter Housing Cap",
  "Oil Filter O-Ring",
  "Oil Level Sensor",
  "Oil Pan",
  "Oil Pan Gasket",
  "Oil Pressure Sensor",
  "Oil Pressure Switch",
  "Oil Pump",
  "Oil Pump Chain",
  "Oil Pump Gear",
  "Oil Pump Seal",
  "Oil Separator",
  "Oil Sump",
  "Oil Temperature Sensor",
  "Oil Tube",
  "O-Ring",
  "Oxygen Sensor",
  "Parking Brake Actuator",
  "Parking Brake Cable",
  "Parking Brake Lever",
  "Parking Brake Motor",
  "Parking Brake Pad",
  "Parking Brake Shoe",
  "Parking Brake Switch",
  "Parking Sensor",
  "Parking Sensor Bracket",
  "Parking Sensor Control Module",
  "PCV Hose",
  "Pedal Assembly",
  "Pedal Pad",
  "Pedal Rubber",
  "Piston",
  "Piston Pin",
  "Piston Ring",
  "Pitman Arm",
  "Power Brake Booster",
  "Power Distribution Box",
  "Power Seat Motor",
  "Power Steering Cooler",
  "Power Steering Hose",
  "Power Steering Line",
  "Power Steering Reservoir",
  "Power Steering Rack",
  "Power Steering Switch",
  "Power Steering Fluid",
  "Power Window Motor",
  "Power Window Regulator",
  "Power Window Switch",
  "Pressure Plate",
  "Pressure Sensor",
  "Propeller Shaft Bearing",
  "Propeller Shaft Coupling",
  "Propeller Shaft Flange",
  "Propeller Shaft Joint",
  "Pulley",
  "Pulley Bearing",
  "Push Rod",
  "Push Rod Tube",
  "Push Button",
  "Push Clip",
  "Push Pin",
  "Push Start Button",
  "Push Start Switch",
  "Pusher Fan",
  "Pusher Fan Motor",
  "Quarter Glass",
  "Quarter Panel",
  "Quarter Panel Glass",
  "Quarter Panel Trim",
  "Quarter Window",
  "Quarter Window Seal",
  "Quick Coupler",
  "Quick Release Coupling",
  "Radiator Cap",
  "Radiator Drain Plug",
  "Radiator Fan Assembly",
  "Radiator Fan Motor",
  "Radiator Fan Relay",
  "Radiator Fan Shroud",
  "Radiator Grille",
  "Radiator Hose",
  "Radiator Mount",
  "Radiator Support",
  "Radiator Support Bracket",
  "Radiator Temperature Sensor",
  "Rear Axle",
  "Rear Axle Shaft",
  "Rear Bumper Cover",
  "Rear Bumper Reinforcement",
  "Rear Caliper",
  "Rear Camera",
  "Rear Coil Spring",
  "Rear Control Arm",
  "Rear Differential",
  "Rear Door Glass",
  "Rear Door Handle",
  "Rear Door Lock",
  "Rear Door Speaker",
  "Rear Door Trim",
  "Rear Fog Light",
  "Rear Hatch",
  "Rear Hatch Handle",
  "Rear Hatch Lock",
  "Rear Hub",
  "Rear Hub Bearing",
  "Rear Lamp",
  "Rear Lower Control Arm",
  "Rear Main Seal",
  "Rear Muffler",
  "Rear Quarter Panel",
  "Rear Shock Absorber",
  "Rear Stabilizer Link",
  "Rear Stabilizer Bar",
  "Rear Strut",
  "Rear Tail Light",
  "Rear Tie Rod",
  "Rear Upper Control Arm",
  "Rear View Camera",
  "Rear View Mirror",
  "Rear Wiper Arm",
  "Rear Wiper Blade",
  "Rear Wiper Motor",
  "Rear Wiper Nozzle",
  "Receiver Drier",
  "Relay Box",
  "Relay Holder",
  "Remote Control",
  "Remote Key",
  "Resonator",
  "Resonator Pipe",
  "Reverse Light",
  "Reverse Light Bulb",
  "Ring Gear",
  "Rocker Arm",
  "Rocker Arm Cover",
  "Rocker Arm Shaft",
  "Rocker Panel",
  "Roof Antenna",
  "Roof Console",
  "Roof Liner",
  "Roof Moulding",
  "Roof Rack",
  "Roof Rack Bar",
  "Roof Rail",
  "Roof Spoiler",
  "Rotor",
  "Rotor Bearing",
  "Rotor Cap",
  "Rotor Seal",
  "Seat Belt Buckle",
  "Seat Belt Pretensioner",
  "Seat Belt Retractor",
  "Seat Cover",
  "Seat Cushion",
  "Seat Heater",
  "Seat Memory Module",
  "Seat Motor",
  "Seat Rail",
  "Seat Recliner",
  "Seat Slide",
  "Seat Switch",
  "Seat Track",
  "Seat Ventilation Fan",
  "Secondary Air Injection Pump",
  "Secondary Air Injection Valve",
  "Selector Cable",
  "Selector Lever",
  "Selector Module",
  "Shift Actuator",
  "Shift Cable",
  "Shift Fork",
  "Shift Knob",
  "Shift Lever",
  "Shift Linkage",
  "Shift Solenoid",
  "Shock Absorber Bushing",
  "Shock Absorber Mount",
  "Shock Absorber Top Mount",
  "Shock Dust Boot",
  "Side Airbag",
  "Side Mirror Glass",
  "Side Mirror Motor",
  "Side Mirror Switch",
  "Side Marker Lamp",
  "Side Skirt",
  "Side Skirt Clip",
  "Side Skirt Moulding",
  "Side Step",
  "Side Step Bracket",
  "Side Step Motor",
  "Side Window Glass",
  "Skid Plate",
  "Slave Cylinder",
  "Slip Ring",
  "Slip Yoke",
  "Smog Pump",
  "Solenoid",
  "Solenoid Valve",
  "Spare Wheel",
  "Spare Wheel Carrier",
  "Spark Plug",
  "Spark Plug Boot",
  "Spark Plug Coil",
  "Spark Plug Wire",
  "Speaker",
  "Speaker Grille",
  "Speed Sensor",
  "Speedometer",
  "Speedometer Cable",
  "Spindle",
  "Spindle Bearing",
  "Spoiler",
  "Spoiler Actuator",
  "Spoiler Bracket",
  "Stabilizer Bar",
  "Stabilizer Bar Bushing",
  "Stabilizer Link",
  "Starter Motor Solenoid",
  "Starter Relay",
  "Steering Column Bearing",
  "Steering Column Motor",
  "Steering Column Shaft",
  "Steering Coupler",
  "Steering Damper",
  "Steering Gear",
  "Steering Knuckle",
  "Steering Rack Boot",
  "Steering Rack Mount",
  "Steering Shaft",
  "Steering Shaft Coupling",
  "Steering Switch",
  "Steering Tie Rod",
  "Steering Wheel Airbag",
  "Steering Wheel Button",
  "Steering Wheel Cover",
  "Steering Wheel Control Module",
  "Steering Wheel Heater",
  "Strut",
  "Strut Bearing",
  "Strut Boot",
  "Strut Mount",
  "Strut Spring",
  "Subframe",
  "Subframe Bushing",
  "Subframe Mount",
  "Sun Visor",
  "Sun Visor Clip",
  "Sunroof",
  "Sunroof Cable",
  "Sunroof Drain Hose",
  "Sunroof Glass",
  "Sunroof Motor",
  "Sunroof Seal",
  "Suspension Arm",
  "Suspension Ball Joint",
  "Suspension Compressor",
  "Suspension Control Module",
  "Suspension Height Sensor",
  "Suspension Link",
  "Suspension Mount",
  "Suspension Spring",
  "Suspension Strut",
  "Suspension Valve Block",
  "Sway Bar",
  "Sway Bar Bushing",
  "Sway Bar Link",
  "Switch",
  "Switch Assembly",
  "Switch Bezel",
  "Switch Connector",
  "Tailgate",
  "Tailgate Actuator",
  "Tailgate Handle",
  "Tailgate Hinge",
  "Tailgate Latch",
  "Tailgate Lock",
  "Tailgate Lock Actuator",
  "Tailgate Striker",
  "Tailgate Strut",
  "Tailgate Trim",
  "Tailgate Weatherstrip",
  "Tail Lamp",
  "Tail Lamp Assembly",
  "Tail Lamp Bulb",
  "Tank",
  "Thermostat Housing",
  "Thermostat Housing Gasket",
  "Thermostat Seal",
  "Throttle Body Gasket",
  "Throttle Position Sensor",
  "Throttle Valve",
  "Tie Rod Boot",
  "Timing Belt Cover",
  "Timing Belt Idler",
  "Timing Belt Kit",
  "Timing Belt Tensioner",
  "Timing Chain Guide",
  "Timing Chain Kit",
  "Timing Chain Tensioner",
  "Timing Cover",
  "Timing Gear",
  "Timing Sprocket",
  "Tire",
  "Tire Pressure Sensor",
  "Tire Valve",
  "Tire Valve Core",
  "Tire Valve Stem",
  "Torque Converter",
  "Torque Converter Seal",
  "Torque Mount",
  "Torsion Bar",
  "Torsion Bar Bushing",
  "Torsion Bar Key",
  "Traction Battery",
  "Traction Control Module",
  "Traction Motor",
  "Trailer Brake Controller",
  "Trailer Hitch",
  "Trailer Hitch Ball",
  "Trailer Hitch Cover",
  "Trailer Hitch Receiver",
  "Trailer Wiring Harness",
  "Transmission",
  "Transmission Assembly",
  "Transmission Cooler",
  "Transmission Cooler Hose",
  "Transmission Cooler Line",
  "Transmission Control Module",
  "Transmission Filter",
  "Transmission Filter Housing",
  "Transmission Fluid",
  "Transmission Pan",
  "Transmission Pan Gasket",
  "Transmission Pressure Sensor",
  "Transmission Range Sensor",
  "Transmission Seal",
  "Transmission Shift Cable",
  "Transmission Solenoid",
  "Transmission Speed Sensor",
  "Transfer Case",
  "Transfer Case Chain",
  "Transfer Case Control Module",
  "Transfer Case Gear",
  "Transfer Case Motor",
  "Transfer Case Seal",
  "Transfer Case Shift Actuator",
  "Turbocharger Actuator",
  "Turbocharger Boost Control Valve",
  "Turbocharger Gasket",
  "Turbocharger Intercooler",
  "Turbocharger Oil Feed Line",
  "Turbocharger Oil Return Line",
  "Turbocharger Repair Kit",
  "Turbocharger Wastegate",
  "Turn Signal",
  "Turn Signal Bulb",
  "Turn Signal Relay",
  "Turn Signal Switch",
  "U-Joint",
  "U-Joint Bearing",
  "U-Joint Cross",
  "U-Joint Flange",
  "U-Joint Kit",
  "Upper Ball Joint",
  "Upper Control Arm",
  "Upper Control Arm Bushing",
  "Upper Radiator Hose",
  "Upper Suspension Arm",
  "USB Charging Port",
  "USB Module",
  "USB Socket",
  "Universal Joint",
  "Universal Joint Bearing",
  "Vacuum Actuator",
  "Vacuum Booster",
  "Vacuum Check Valve",
  "Vacuum Hose",
  "Vacuum Reservoir",
  "Vacuum Solenoid",
  "Vacuum Switching Valve",
  "Vacuum Tank",
  "Valve",
  "Valve Body",
  "Valve Body Gasket",
  "Valve Cover",
  "Valve Guide",
  "Valve Keeper",
  "Valve Lift Control Motor",
  "Valve Retainer",
  "Valve Seal",
  "Valve Spring",
  "Valve Stem",
  "Valve Stem Seal",
  "Variable Valve Timing Actuator",
  "Variable Valve Timing Control Solenoid",
  "Variable Valve Timing Gear",
  "Variable Valve Timing Sensor",
  "Vent Hose",
  "Vent Valve",
  "Ventilation Fan",
  "Voltage Regulator",
  "Washer Fluid",
  "Washer Fluid Reservoir",
  "Washer Level Sensor",
  "Washer Motor",
  "Washer Nozzle",
  "Washer Pump",
  "Washer Tank",
  "Water Pump Belt",
  "Water Pump Gasket",
  "Water Pump Pulley",
  "Water Pump Seal",
  "Water Separator",
  "Water Temperature Sensor",
  "Weatherstrip",
  "Wheel",
  "Wheel Arch Liner",
  "Wheel Bearing Hub",
  "Wheel Bolt",
  "Wheel Center Cap",
  "Wheel Hub Bearing",
  "Wheel Hub Cap",
  "Wheel Lug Nut",
  "Wheel Rim",
  "Wheel Seal",
  "Wheel Speed Sensor",
  "Wheel Spacer",
  "Wheel Stud",
  "Wheel Trim",
  "Window Channel",
  "Window Glass",
  "Window Glass Regulator",
  "Window Lift Motor",
  "Window Regulator",
  "Window Regulator Cable",
  "Window Regulator Clip",
  "Window Regulator Motor",
  "Window Seal",
  "Window Switch",
  "Window Weatherstrip",
  "Windshield",
  "Windshield Washer Hose",
  "Windshield Washer Nozzle",
  "Windshield Washer Pump",
  "Windshield Wiper Arm",
  "Windshield Wiper Blade",
  "Windshield Wiper Linkage",
  "Windshield Wiper Motor",
  "Windshield Wiper Relay",
  "Windshield Wiper Switch",
  "Windshield Wiper Transmission",
  "Wing Mirror",
  "Wing Mirror Actuator",
  "Wing Mirror Glass",
  "Wing Mirror Housing",
  "Wiring Harness Connector",
  "Wiring Repair Kit",
  "X-Pipe",
  "Xenon Bulb",
  "Xenon Headlamp",
  "Xenon Headlamp Control Module",
  "Xenon Igniter",
  "Y-Pipe",
  "Yaw Rate Sensor",
  "Yaw Sensor",
  "Yoke",
  "Yoke Bearing",
  "Yoke Seal",
  "Z-Bar",
  "Zinc Anode",
  "Zipper Seat Cover",
  "Zone Control Actuator",
  "Zone Control Module",
  "Zone Temperature Sensor",
];

// Combined list (kept for anything that wants the full catalogue).
export const CAR_PARTS: string[] = [...AUTO_PARTS, ...BODY_PARTS, ...MASTER_PARTS];
